<a href="https://colab.research.google.com/github/javier290595/AID/blob/main/Array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
a=np.array([[1, 2, 3], [4, 5, 6]])
print(a[1, 0])
print(a[1][0])
print(a[:, 0:2])


4
4
[[1 2]
 [4 5]]


In [4]:
a=np.array([[1, 2, 3], [4, 5, 6]])
print(a[(a% 2 == 0)])
print(a[(a% 2 == 0) &  (a> 2)])

[2 4 6]
[4 6]


In [5]:
a=np.array([[1, 2, 3], [4, 5, 6]])
b=np.array([[1, 1, 1], [2, 2, 2]])
print(a+b)

[[2 3 4]
 [6 7 8]]


In [6]:
print(a/b)

[[1.  2.  3. ]
 [2.  2.5 3. ]]


In [7]:
print(a** 2)

[[ 1  4  9]
 [16 25 36]]
