<a href="https://colab.research.google.com/github/javier290595/AID/blob/main/ejercicios_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
#Arraydeunadimensión
import numpy as np

a1= np.array([1, 2, 3])
print(a1)

[1 2 3]


In [7]:
#Arraydedosdimensiones
a2=np.array([[1, 2, 3], [4, 5, 6]])
print(a2)


[[1 2 3]
 [4 5 6]]


In [8]:
#Arraydetresdimensiones
a3=np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(a3)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [18]:
print(np.zeros((3,2)))

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [25]:
print(np.identity(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [26]:
print (np.arange(1,10,2))

[1 3 5 7 9]


In [27]:
print (np.linspace(0,10,5))

[ 0.   2.5  5.   7.5 10. ]
